using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Demo_UserDefinedExceptions
{
    /// <summary>
    /// Demo of implementing user-defined exceptions generated by the model
    /// </summary>
    class Program
    {
        static void Main(string[] args)
        {
            //
            // declare variables and set initial state of all flags
            //
            int row, column;
            bool validMove = false;
            bool playingRound = true;

            //
            // initialize the game board
            //
            Gameboard myGameboard = new Gameboard();
            myGameboard.CurrentRoundState = Gameboard.GameboardState.PlayerOTurn;

            //
            // round loop
            //
            while (playingRound)
            {
                validMove = false;

                //
                // player move loop
                //
                while (!validMove)
                {
                    //
                    // display which player's turn it is
                    //
                    Console.WriteLine("Player: " + myGameboard.CurrentRoundState.ToString());

                    //
                    // get row and column values from player
                    // Note: no validation
                    //
                    Console.Write("Row:");
                    row = int.Parse(Console.ReadLine());
                    Console.Write("Column:");
                    column = int.Parse(Console.ReadLine());

                    //
                    // insert try/catch/catch block here
                    //
                }
            }
        }
    }
}
